# Generated by Django 5.2.5 on 2025-09-16

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    # Create the groups if they don't exist
    Group.objects.get_or_create(name='cliente')
    Group.objects.get_or_create(name='admin')
    Group.objects.get_or_create(name='editor')


def reverse_groups(apps, schema_editor):
    # Remove the groups if they exist
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['cliente', 'admin', 'editor']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_groups),
    ]