# Generated by Django 5.2.3 on 2025-08-23 07:57

import config.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], help_text='Estado de conservación según la clasificación IUCN', max_length=30, unique=True, verbose_name='Estado de Conservación')),
            ],
            options={
                'verbose_name': 'Estado de Conservación',
                'verbose_name_plural': 'Estados de Conservación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del hábitat', max_length=50, unique=True, verbose_name='Nombre')),
                ('capacity', models.PositiveIntegerField(help_text='Capacidad máxima de animales', verbose_name='Capacidad')),
                ('description', models.TextField(help_text='Descripción detallada del hábitat', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Hábitat',
                'verbose_name_plural': 'Hábitats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre común de la especie', max_length=100, unique=True, verbose_name='Nombre Común')),
                ('scientific_name', models.CharField(help_text='Nombre científico de la especie (género y especie)', max_length=100, unique=True, verbose_name='Nombre Científico')),
                ('description', models.TextField(help_text='Descripción detallada de la especie', verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, help_text='Imagen representativa de la especie', null=True, storage=config.storage_backends.MediaStorage(), upload_to='species/', verbose_name='Imagen')),
                ('conservation_status', models.ForeignKey(help_text='Estado actual de conservación de la especie', on_delete=django.db.models.deletion.PROTECT, related_name='species', to='wildlife.conservationstatus', verbose_name='Estado de Conservación')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del animal', max_length=50, verbose_name='Nombre')),
                ('age', models.PositiveIntegerField(help_text='Edad del animal en años', verbose_name='Edad')),
                ('habitat', models.ForeignKey(help_text='Hábitat donde reside el animal', on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='wildlife.habitat', verbose_name='Hábitat')),
                ('specie', models.ForeignKey(help_text='Especie a la que pertenece el animal', on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='wildlife.specie', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['name'],
            },
        ),
    ]
