# Generated by Django 5.2.3 on 2025-09-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_auto_20250916_2252'),
        ('wildlife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='nums_animals',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Number of Animals'),
        ),
        migrations.AddField(
            model_name='habitat',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Sección a la que pertenece el hábitat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitats', to='infrastructure.sections', verbose_name='Sección'),
        ),
    ]
