# Generated by Django 5.2.3 on 2025-08-22 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto original de la donación', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', help_text='Moneda original de la donación', max_length=3)),
                ('monto_crc', models.DecimalField(decimal_places=2, help_text='Monto convertido a Colones', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto convertido a Dólares', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_donante', models.CharField(blank=True, max_length=100, null=True)),
                ('email_donante', models.EmailField(blank=True, max_length=254, null=True)),
                ('metodo_pago', models.CharField(choices=[('CARD', 'Tarjeta de Crédito/Débito'), ('PAYPAL', 'PayPal'), ('CASH', 'Efectivo/SINPE'), ('TRANSFER', 'Transferencia Bancaria'), ('OTHER', 'Otro')], max_length=30)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SUCCESS', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto en la moneda seleccionada', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_crc', models.DecimalField(decimal_places=2, help_text='Monto en Colones', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto en Dólares', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', max_length=3)),
                ('metodo_pago', models.CharField(choices=[('CARD', 'Tarjeta de Crédito/Débito'), ('PAYPAL', 'PayPal'), ('CASH', 'Efectivo/SINPE'), ('TRANSFER', 'Transferencia Bancaria'), ('OTHER', 'Otro')], max_length=20)),
                ('referencia_transaccion', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SUCCESS', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PagoInscripcion',
            fields=[
                ('pago_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.pago')),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='education.inscripcion')),
            ],
            options={
                'verbose_name': 'Pago de Inscripción',
                'verbose_name_plural': 'Pagos de Inscripciones',
            },
            bases=('payments.pago',),
        ),
    ]
