# Generated by Django 5.2.3 on 2025-08-23 07:57

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, storage=config.storage_backends.MediaStorage(), upload_to='comprobantes_pago/'),
        ),
    ]
