# Generated by Django 5.2.3 on 2025-08-22 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('cupos_disponibles', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion_horas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacidad_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacidad_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('edad_minima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('edad_maxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('requisitos', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programa Educativo',
                'verbose_name_plural': 'Programas Educativos',
            },
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='programas/')),
            ],
            options={
                'verbose_name': 'Programa Educativo',
                'verbose_name_plural': 'Programas Educativos',
            },
        ),
        migrations.CreateModel(
            name='ServiciosEducativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Servicio Educativo',
                'verbose_name_plural': 'Servicios Educativos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=200)),
                ('edad_participante', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='education.horario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_asignados', to='education.instructor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='education.programa'),
        ),
        migrations.CreateModel(
            name='ProgramaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='education.programaeducativo')),
            ],
            options={
                'verbose_name': 'Item de Programa',
                'verbose_name_plural': 'Items de Programas',
            },
        ),
        migrations.CreateModel(
            name='ServiciosEducativosButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='education.servicioseducativos')),
            ],
            options={
                'verbose_name': 'Botón de Servicio Educativo',
                'verbose_name_plural': 'Botones de Servicios Educativos',
            },
        ),
        migrations.CreateModel(
            name='ServiciosEducativosDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='education.servicioseducativos')),
            ],
            options={
                'verbose_name': 'Descripción de Servicio Educativo',
                'verbose_name_plural': 'Descripciones de Servicios Educativos',
            },
        ),
        migrations.CreateModel(
            name='ServiciosEducativosFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='education.servicioseducativos')),
            ],
            options={
                'verbose_name': 'Dato de Servicio Educativo',
                'verbose_name_plural': 'Datos de Servicios Educativos',
            },
        ),
        migrations.CreateModel(
            name='ServiciosEducativosImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='servicios-educativos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='education.servicioseducativos')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio Educativo',
                'verbose_name_plural': 'Imágenes de Servicios Educativos',
            },
        ),
    ]
