# Generated by Django 5.2.3 on 2025-08-23 07:57

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaeducativo',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.MediaStorage(), upload_to='programas/'),
        ),
        migrations.AlterField(
            model_name='servicioseducativosimage',
            name='image',
            field=models.ImageField(storage=config.storage_backends.MediaStorage(), upload_to='servicios-educativos/'),
        ),
    ]
