# Generated by Django 5.2.3 on 2025-08-23 07:40

import config.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del documento', max_length=200)),
                ('tipo', models.CharField(choices=[('REPORT', 'Informe'), ('POLICY', 'Política'), ('MANUAL', 'Manual'), ('CONTRACT', 'Contrato'), ('OTHER', 'Otro')], help_text='Tipo de documento', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del documento')),
                ('archivo', models.FileField(help_text='Archivo del documento', storage=config.storage_backends.MediaStorage(), upload_to='documentos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', help_text='Versión del documento', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=200)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VERSION', 'Nueva Versión')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción del cambio realizado')),
                ('version_anterior', models.CharField(blank=True, help_text='Versión anterior del documento', max_length=50)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='documents.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Documento',
                'verbose_name_plural': 'Historial de Documentos',
                'ordering': ['-fecha'],
            },
        ),
    ]
