# Generated by Django 5.2.3 on 2025-08-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tamano_archivo',
            field=models.CharField(blank=True, help_text='Tamaño del archivo en formato legible', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_archivo',
            field=models.CharField(blank=True, help_text='Tipo de archivo (calculado automáticamente)', max_length=10, null=True),
        ),
    ]
