# Generated by Django 5.2.3 on 2025-08-21 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Identificador único de la exhibición', max_length=255, unique=True, verbose_name='Valor')),
                ('label', models.CharField(help_text='Etiqueta descriptiva de la exhibición', max_length=255, unique=True, verbose_name='Etiqueta')),
                ('title', models.CharField(help_text='Título principal de la exhibición', max_length=255, unique=True, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Exhibición',
                'verbose_name_plural': 'Exhibiciones',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ExhibicionButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto que se mostrará en el botón', max_length=255, unique=True, verbose_name='Etiqueta')),
                ('link', models.CharField(blank=True, default='', help_text='URL a la que dirigirá el botón', max_length=255, unique=True, verbose_name='Enlace')),
                ('exhibicion', models.ForeignKey(help_text='Exhibición a la que pertenece el botón', on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='exhibitions.exhibicion', verbose_name='Exhibición')),
            ],
            options={
                'verbose_name': 'Botón de exhibición',
                'verbose_name_plural': 'Botones de exhibiciones',
            },
        ),
        migrations.CreateModel(
            name='ExhibicionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Texto descriptivo de la exhibición', verbose_name='Descripción')),
                ('exhibicion', models.ForeignKey(help_text='Exhibición a la que pertenece la descripción', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='exhibitions.exhibicion', verbose_name='Exhibición')),
            ],
            options={
                'verbose_name': 'Descripción de exhibición',
                'verbose_name_plural': 'Descripciones de exhibiciones',
            },
        ),
        migrations.CreateModel(
            name='ExhibicionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField(help_text='Dato o hecho interesante sobre la exhibición', verbose_name='Dato interesante')),
                ('exhibicion', models.ForeignKey(help_text='Exhibición a la que pertenece el dato', on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='exhibitions.exhibicion', verbose_name='Exhibición')),
            ],
            options={
                'verbose_name': 'Dato de exhibición',
                'verbose_name_plural': 'Datos de exhibiciones',
            },
        ),
        migrations.CreateModel(
            name='ExhibicionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Archivo de imagen de la exhibición', upload_to='exhibitions/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('exhibicion', models.ForeignKey(help_text='Exhibición a la que pertenece la imagen', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibitions.exhibicion', verbose_name='Exhibición')),
            ],
            options={
                'verbose_name': 'Imagen de exhibición',
                'verbose_name_plural': 'Imágenes de exhibiciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
