# Generated by Django 5.2.3 on 2025-08-23 07:57

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibicionimage',
            name='image',
            field=models.ImageField(help_text='Archivo de imagen de la exhibición', storage=config.storage_backends.MediaStorage(), upload_to='exhibitions/', verbose_name='Imagen'),
        ),
    ]
