# Generated by Django 5.2.3 on 2025-08-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Section Name')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Habitats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Habitat Name')),
                ('nums_animals', models.PositiveIntegerField(verbose_name='Number of Animals')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitats', to='infrastructure.sections')),
            ],
            options={
                'verbose_name': 'Habitat',
                'verbose_name_plural': 'Habitats',
                'ordering': ['name'],
            },
        ),
    ]
