# Generated by Django 5.2.3 on 2025-09-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habitats',
        ),
    ]