# Generated by Django 5.2.3 on 2025-09-12 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('registration', 'User Registration'), ('login', 'User Login'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
                'db_table': 'otp_records',
                'indexes': [models.Index(fields=['phone_number', 'otp_code'], name='otp_records_phone_n_493201_idx'), models.Index(fields=['user', 'purpose'], name='otp_records_user_id_ac6f94_idx')],
            },
        ),
    ]
