# Generated by Django 5.2.3 on 2025-08-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Ticket')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre del Ticket')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('total_slots', models.PositiveIntegerField(default=1276, verbose_name='Cupos Totales')),
                ('occupied_slots', models.PositiveIntegerField(default=0, verbose_name='Cupos Ocupados')),
                ('currency', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', max_length=3, verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='Día de Visita')),
                ('total_slots', models.PositiveIntegerField(default=1276, verbose_name='Cupos Totales')),
                ('occupied_slots', models.PositiveIntegerField(default=0, verbose_name='Cupos Ocupados')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-day'],
            },
        ),
    ]
